description: Official Elastic helm chart for Filebeat
home: https://github.com/elastic/helm-charts
maintainers:
- email: helm-charts@elastic.co
  name: Elastic
name: filebeat
version: 7.3.0
appVersion: 7.3.0
sources:
  - https://github.com/elastic/beats
icon: https://helm.elastic.co/icons/filebeat.png
