---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "kibana.fullname" . }}-helm-scripts
  labels: {{ include "kibana.labels" . | nindent 4 }}
data:
  kibana-entrypoint.sh: |
    export ELASTICSEARCH_SERVICEACCOUNTTOKEN=$(/usr/share/kibana/node/bin/node /usr/share/kibana/helm-scripts/parse-token.js)

    # https://github.com/elastic/dockerfiles/blob/a405a4d692031b72cefcb8523bd464aa3221ec47/kibana/Dockerfile#L131
    exec /bin/tini -- /usr/local/bin/kibana-docker "$@"

  parse-token.js: |
    let dataFile = require('/usr/share/kibana/config/tokens/kb-kibana.json');
    console.log(dataFile.token.value);
