{{- if .Values.rbac.create -}}
{{- $fullName := include "kibana.fullname" . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ template "kibana.serviceAccount" . }}"
  annotations:
    {{- with .Values.rbac.serviceAccountAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels: {{ include "kibana.labels" . | nindent 4 }}
{{- end -}}