metricbeatConfig:
  metricbeat.yml: |
    system:
      hostfs: /hostfs
    metricbeat.modules:
    - module: kubernetes
      labels.dedot: true
      annotations.dedot: true
      add_metadata: true
      in_cluster: true
      metricsets:
        - container
        - node
        - pod
        - system
        - volume
      period: 10s
      host: "${NODE_NAME}"
      hosts: ["${NODE_NAME}:10255"]
      # This config is how metricbeat talks to the kubelet. There are two ports available-
      # 10255 for read-only / insecure comms and 10250 for tls comms. Depending on your k8s
      # config, you may need to use the commented config with port 10250 and the ssl secrets
      # The final consideration is the hostname- ${NODE_NAME} needs to be dns resolvable.
      # with host networking, localhost could work here on 10255- but the certs on 10250
      # will be rejected with the `localhost` hostname (unless you set verify = false)
      # hosts: ["https://${NODE_NAME}:10250"]
      # bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      # ssl.certificate_authorities:
      #   - /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    - module: kubernetes
      enabled: true
      add_metadata: true
      in_cluster: true
      # without the `dedot` settings, annotations or labels such as `kubernetes.io: some-annotation`
      # will not validate
      labels.dedot: true
      annotations.dedot: true
      metricsets:
        - event
    - module: system
      period: 10s
      metricsets:
        - cpu
        - load
        - memory
        - network
        - process
        - process_summary
      processes: ['.*']
      process.include_top_n:
        by_cpu: 5
        by_memory: 5
    - module: system
      period: 1m
      metricsets:
        - filesystem
        - fsstat
      processors:
      - drop_event.when.regexp:
          system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib)($|/)'

    output.elasticsearch:
      username: '${ELASTICSEARCH_USERNAME}'
      password: '${ELASTICSEARCH_PASSWORD}'
      protocol: https
      hosts: ["security-master:9200"]
      ssl.certificate_authorities:
        - /usr/share/metricbeat/config/certs/elastic-certificate.pem

  kube-state-metrics-metricbeat.yml: |
    metricbeat.modules:
    - module: kubernetes
      enabled: true
      labels.dedot: true
      annotations.dedot: true
      add_metadata: true
      in_cluster: true
      metricsets:
        - state_node
        - state_deployment
        - state_replicaset
        - state_statefulset
        - state_pod
        - state_container
      period: 10s
      host: ${NODE_NAME}
      hosts: ["${KUBE_STATE_METRICS_HOSTS}"]
    output.elasticsearch:
      username: '${ELASTICSEARCH_USERNAME}'
      password: '${ELASTICSEARCH_PASSWORD}'
      protocol: https
      hosts: ["security-master:9200"]
      ssl.certificate_authorities:
        - /usr/share/metricbeat/config/certs/elastic-certificate.pem

secretMounts:
  - name: elastic-certificate-pem
    secretName: elastic-certificate-pem
    path: /usr/share/metricbeat/config/certs

extraEnvs:
  - name: 'ELASTICSEARCH_USERNAME'
    valueFrom:
      secretKeyRef:
        name: elastic-credentials
        key: username
  - name: 'ELASTICSEARCH_PASSWORD'
    valueFrom:
      secretKeyRef:
        name: elastic-credentials
        key: password
