{{- if .Values.metrics and .Values.metrics.PodMonitor }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ template "filebeat.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: "{{ template "filebeat.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app: "{{ template "filebeat.fullname" . }}"
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  podMetricsEndpoints:
  - interval: {{ .Values.metrics.podMonitor.interval }}
  {{- if .Values.metrics.podMonitor.portName }}
    port: {{ .Values.metrics.podMonitor.portName }}
  {{- end }}
  {{- if .Values.metrics.podMonitor.scrapeTimeout }}
    scrapeTimeout: {{ .Values.metrics.podMonitor.scrapeTimeout }}
  {{- end }}
{{- end }}
