networkPolicy:
  http:
    enabled: true
    explicitNamespacesSelector:
      # Accept from namespaces with all those different rules (from whitelisted Pods)
      matchLabels:
        role: frontend
      matchExpressions:
        - {key: role, operator: In, values: [frontend]}
    additionalRules:
      - podSelector:
          matchLabels:
            role: frontend
      - podSelector:
          matchExpressions:
            - key: role
              operator: In
              values:
                - frontend
  transport:
    enabled: true
    allowExternal: true
    explicitNamespacesSelector:
      matchLabels:
        role: frontend
      matchExpressions:
        - {key: role, operator: In, values: [frontend]}
    additionalRules:
      - podSelector:
          matchLabels:
            role: frontend
      - podSelector:
          matchExpressions:
            - key: role
              operator: In
              values:
                - frontend
