description: Elasticsearch
home: https://github.com/elastic/helm-charts
maintainers:
- email: helm-charts@elastic.co
  name: Elastic
name: elasticsearch
version: 7.0.1-alpha1
appVersion: 7.0.1
sources:
  - https://github.com/elastic/elasticsearch
icon: https://helm.elastic.co/icons/elasticsearch.png
