image: docker.elastic.co/apm/apm-server-oss

apmConfig:
  apm-server.yml: |
    apm-server:
      host: "0.0.0.0:8200"

    queue: {}
    output.file:
      enabled: false

    output.elasticsearch:
      hosts: ["http://elasticsearch-master:9200"]
      index: "apm-oss-%{[observer.version]}-%{+yyyy.MM.dd}"

    setup.template.name: "apm-server"
    setup.template.pattern: "apm-oss-*"
