apiVersion: v1
description: Official Elastic helm chart for Elastic APM Server
home: https://github.com/elastic/helm-charts
maintainers:
  - email: helm-charts@elastic.co
    name: Elastic
name: apm-server
version: 7.17.3
appVersion: 7.17.3
sources:
  - https://github.com/elastic/apm
icon: https://helm.elastic.co/icons/apm.png
