---
{{- if .Values.maxUnavailable }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: "{{ template "logstash.fullname" . }}-pdb"
  labels: {{- include "logstash.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.maxUnavailable }}
  selector:
    matchLabels:
      app: "{{ template "logstash.fullname" . }}"
{{- end }}
