{{- if .Values.podSecurityPolicy.create -}}
{{- $fullName := include "logstash.fullname" . -}}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ default $fullName .Values.podSecurityPolicy.name | quote }}
  labels: {{- include "logstash.labels" . | nindent 4 }}
spec:
{{ toYaml .Values.podSecurityPolicy.spec | indent 2 }}
{{- end -}}
