---
kind: Service
apiVersion: v1
metadata:
  name: "{{ template "logstash.fullname" . }}-headless"
  labels: {{- include "logstash.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app: "{{ template "logstash.fullname" . }}"
  ports:
    - name: http
      port: {{ .Values.httpPort }}
