{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) -}}
{{- $fullName := include "elasticsearch.uname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName | quote }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ $fullName | quote }}
data:
  {{- if .Values.auth.password }}
  elastic-password: {{ .Values.auth.password | b64enc | quote }}
  {{- else }}
  elastic-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
{{- end -}}